version: "3.9"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ai_shiritori
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build: .
    environment:
      RAILS_ENV: development
      DATABASE_HOST: db
      DATABASE_USER: root
      DATABASE_PASSWORD: password
      REDIS_URL: redis://redis:6379/0
      RAILS_MASTER_KEY: "your_master_key_here"
      GEMINI_API_KEY: "your_gemini_api_key_here"
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    command: bash -c "bundle exec rails s -b 0.0.0.0"

volumes:
  db-data:
